#include <stdio.h>

/**
 * main - fibonacci generated by adding the previous two terms
 *
 * Return: Always 0 (Success)
 */

int main(void)
{
	long long first = 0;
	long long second = 1;
	long long sum = 1;
	long long next = first + second;

	while (next <= 4000000)
	{
		if (next % 2 == 0)
		{
			sum += next;
		}

		first = second;
		second = next;
		next = first + second;
	}

	printf("sum: %lld\n", sum);

	return (0);
}
