#include <stdio.h>

/**
 * main - fibonacci generated by adding the previous two terms
 *
 * Return: Always 0 (Success)
 */

int main(void)
{
	long first = 0;
	long second = 1;
	long sum = 1;
	long next = first + second;

	long limit = 4000000;

	while (1)
	{
		next = first + second;
		if (next > limit)
		{
			break;
		}

		if (next % 2 == 0)
		{
			sum += next;
		}

		first = second;
		second = next;
	}

	printf("sum of evened-value: %ld\n", sum);

	return (0);
}
